name: Feature request
description: Suggest an idea for this project
labels: 'feature request'
body:

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.

- type: markdown
  attributes:
    value: |
      ## Sponsor us

      Thank you very much for your feedback here, but Xmake is a personal open source project.
      Due to the limited time and energy of the author, we cannot guarantee that your feature request will be fulfilled.

      But you can also consider [sponsoring us](https://xmake.io/#/about/sponsor) to accelerate our development of new features, thanks!
