name: 请求新功能
description: 提出你期待的功能特性
labels: 'feature request'
body:

- type: textarea
  id: problem
  attributes:
    label: 你在什么场景下需要该功能？
    description: 请尽量清晰精准地描述你碰到的问题。
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: 描述可能的解决方案
    description: 请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。
  validations:
    required: true

- type: textarea
  id: second-solution
  attributes:
    label: 描述你认为的候选方案
    description: 请尽量清晰精准地描述你能接受的候选解决方案。

- type: textarea
  id: other
  attributes:
    label: 其他信息
    description: 请提供关于该功能建议的其他附加信息。

- type: markdown
  id: sponsor
  attributes:
    value: |
      ## 赞助我们

      非常感谢您能在这里反馈问题，但是 Xmake 是个人开源项目，由于作者的时间精力有限，不一定能够保证您的需求一定会被采纳和实现。

      但是您也可以考虑[赞助我们](https://xmake.io/#/zh-cn/about/sponsor)，来加速我们对新特性的开发，谢谢！
